{% set name = "Werkzeug" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7280924747b5733b246fe23972186c6b348f9ae29724135a6dfc1e53cea433e7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - werkzeug
    - werkzeug.debug

about:
  home: https://palletsprojects.com/p/werkzeug/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: The comprehensive WSGI web application library.
  description: |
    Werkzeug is a WSGI utility library for Python. It's widely used and BSD licensed.
  doc_url: https://werkzeug.palletsprojects.com/
  dev_url: https://github.com/pallets/werkzeug

extra:
  recipe-maintainers:
    - goanpeca
    - mcs07
