{% set name = "Werkzeug" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b353856d37dec59d6511359f97f6a4b2468442e454bd1c98298ddce53cac1f04

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - werkzeug
    - werkzeug.debug

about:
  home: https://palletsprojects.com/p/werkzeug/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: The comprehensive WSGI web application library.
  description: |
    Werkzeug is a WSGI utility library for Python. It's widely used and BSD licensed.
  doc_url: https://werkzeug.palletsprojects.com/
  dev_url: https://github.com/pallets/werkzeug

extra:
  recipe-maintainers:
    - goanpeca
    - mcs07
