{% set name = "Werkzeug" %}
{% set version = "0.12.2" %}
{% set hash_type = "sha256" %}
{% set hash = "903a7b87b74635244548b30d30db4c8947fe64c5198f58899ddcd3a13c23bb26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - werkzeug
    - werkzeug.debug
    - werkzeug.contrib

about:
  home: http://werkzeug.pocoo.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Python WSGI Utility Library.
  description: |
    Werkzeug is a WSGI utility library for Python. It's widely used and BSD licensed.
  doc_url: http://werkzeug.pocoo.org/docs
  dev_url: https://github.com/pallets/werkzeug

extra:
  recipe-maintainers:
    - goanpeca
