{% set name = "Werkzeug" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 097e5bfda9f0aba8da6b8545146def481d06aa7d3266e7448e2cccf67dd8bd18

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -v

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - markupsafe >=2.1.1
  run_constrained:
    - watchdog >=2.3

test:
  imports:
    - werkzeug
    - werkzeug.debug
  # source_files:
  #   - tests
  requires:
    - pip
    # - cryptography
    # - greenlet
    # - pytest
    # - pytest-timeout
    # - types-setuptools
  commands:
    - pip check
    # 'pytest' fails immediately because packages 'ephemeral_port_reserve' and 'pytest-xprocess' are not available on defaults.
    # Additionally, 'pytest-xprocess' requires 'psutil' on linux-aarch64 and linux-s390x
    #- pip install ephemeral_port_reserve pytest-xprocess
    # Skip 'test_basic' and 'test_http_proxy' because of ConnectionRefusedError.
    # Skip 'test_serving.py' because watchdog >=2.3 isn't available
    #- pytest -vv -k "not (exclude_patterns or test_basic or test_http_proxy)" --ignore=tests/test_serving.py

about:
  home: https://palletsprojects.com/p/werkzeug/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The comprehensive WSGI web application library.
  description: |
    Werkzeug is a WSGI utility library for Python. It's widely used and BSD licensed.
  doc_url: https://werkzeug.palletsprojects.com/
  dev_url: https://github.com/pallets/werkzeug

extra:
  recipe-maintainers:
    - goanpeca
    - mcs07
