travis:
  secure:
    BINSTAR_TOKEN: j6W7xKI+ViOS94wEzLFphPwXxLomWRuSrDvw3016tPspqlxAI96zpi3nJUcsAX7jTM0u/u7+nSCeVBhseJAJ4LZVa/iIYXazKBkKQ4laxX0deMeMrIga5/Se53xwDUMkdiosFqGdGWMH7B5IoUpcaTf7I28w8hyfjptgeddCGo4zvBwSIl4JqiCNytdZ/2dk2pFrq88/t4G2k7amWCd7RE8WUAR7e7Xa6KKYnpYF8iX79Atutcww1TXCpQ+WucqaNsq1/hGoNehrHp3tz3BYgVPCpXf6635RpKGMajLoEsoyuGdVkN7I+wZpdH5Pu6ibFZ83Ha14+HgzDfbwRL1smNo+Ou+2gu1y0evobOvw24nFXtpOs6vdvcwqi+BorkUN9wNNNt3IbLCRCzRtLX05N1G9+NXsxqZ438l+IlHng36sRWBiwlFvrHzwhvYayVaQqQsr+ZlHEzQePrdO3WgtElkYvfdZuxIm4taVqlCmY2tPDrRRf3J4YX2nPjuhT1+5y5r8ETtnlVpc6xHd+37b6t0nVVtHO4IVjLFTLZbuGFHCRBpS7mlvLzPn6KR1VgTA8xPhOUaw+xOifK2T8qe/DsIoAneg2+hmmP75yS6/Y3YCqMcdh/wW1vKXPSd/8FBJA45konGgcJUfeAKKXM8Rn2vNdthi3P9dpi0+di4sc2g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
