travis:
  secure:
    BINSTAR_TOKEN: tmR+q7lQayJz4UHh6DGi41uUME9S2KxRAyVTC/iRuCHb/4UDkI7aEKilb/lkf/aUnGADOrfKWM41BJlWSQs+j6Gij60xG+cLaUe8cbtl2qmmNRRhdsWrmbczpintOUntP0MElrDyCSjBBq7jrAMXQtNyjWnUuQnpMz3mJtiNhiV5mdpGH3uZjrAIslBXBVfI9sxa/yhW8unHVLOVJvbdMPgBK/hawlyj+eu8iWr/m3KYyxvLvpGftmChwEmNqvcw5TtWRfQebaGc3b/8b0utVp7v4Rp4FZrRr/Keism0miUTTV8C8n+5Y+iiFYVRBslila/rIwqwGEdJO/sy2EuUP7rNdpxCCEt1drweijrHCTjnG37+s6TMurgN1aBGMpZQpgzOxUFSPicoiFr7gg2BczaxnEfjRvSg77gJiKjAAUnJzykrMAGSNU2tu7mfasaQPzA2izJ5gJGRVzsg4gnHJ0L2N22vWULvuMq5RAfccSM5rPfodGcs9m8oQrhK84t41ld2GTGw7j3IGkjVNC3JRQSMOD2ddIB7YyY79AkUzZ27SYB9Q+m/ueAJxSLkq9rL8gWbgM/si8exDZCrx5zSn0Yw1u484bRaTHItlwui2IbLsW50JGVOnrcyQkN5xnS0FN1aClhF1T55p3c1v1YHw5Sm3QFsZ1azewESn1ikjWc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
